%进行FFT变换并做频谱图
function [] = plot_figure(x,N,fs)
y=fft(x,N);%进行fft变换
mag=abs(y);%求幅值

f=(0:length(y)-1)'*fs/length(y);%进行对应的频率转换
figure(1);
subplot(221);
plot(f,mag);%做频谱图
axis([0,100,0,80]);
xlabel('频率(Hz)');
ylabel('幅值');
title('频谱图N=128');
grid;
%求均方根谱
sq=abs(y);
figure(1);
subplot(222);
plot(f,sq);
xlabel('频率(Hz)');
ylabel('均方根谱');
title('均方根谱');
grid;
%求功率谱
power=sq.^2;
figure(1);
subplot(223);
plot(f,power);
xlabel('频率(Hz)');
ylabel('功率谱');
title('功率谱');
%用IFFT恢复原始信号
xifft=ifft(y);
magx=real(xifft);
ti=[0:length(xifft)-1]/fs;
figure(1);
subplot(224);
plot(ti,magx);
xlabel('t');
ylabel('y');
title('IFFT转换的波形');